# Generated by Django 4.1 on 2022-08-17 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Todolist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("todo", models.TextField()),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="users_todolist", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
