# Generated by Django 4.1 on 2022-08-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="profile_photos/photoretouches.jpeg",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
    ]
