# Generated by Django 4.1 on 2022-08-07 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sleep_hours", models.IntegerField()),
                ("javascript_hours", models.IntegerField()),
                ("python_hours", models.IntegerField()),
                ("mathematics_learning_time", models.IntegerField()),
                ("javascript_testing_hours", models.IntegerField()),
                ("python_testing_hours", models.IntegerField()),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="users_statistics", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "javascript_learning_links",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "python_learning_links",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "javascript_testing_links",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "python_testing_links",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "javascript_solved_problems_links",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "python_solved_problems_links",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="users_links", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
